///code generated by chatgpt, the prompt is "generate a code for the smooth color gradient process in the slider component with max and min value and decrease by time, 
/// with color-change thresholds of 65% and 20%. and play an audio that based on health goes from 20% to 0%,
/// and play another audio file when health goes 65% to 20%,gradually increasing in volume and speed on the first one and increasing volume only on second one."
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class BarGradient : MonoBehaviour
{
    public Slider Slider1;
    public Image fillImage;
    public AudioSource audioSourceLow;
    public AudioSource audioSourceMedium;
    public Color safe = Color.green;
    public Color meh = Color.yellow;
    public Color danger = Color.gray;
    public static float healthValue;

    void Start()
    {
        healthValue = Slider1.maxValue;
        Slider1.value = healthValue;
        UpdateFillColor(Slider1.value);
    }

    void Update()
    {
        Slider1.value -= Time.deltaTime;
        if (Slider1.value < 0)
        {
            Slider1.value = 0;
        }
        healthValue = Slider1.value;
        UpdateFillColor(Slider1.value);
        UpdateAudio(Slider1.value / Slider1.maxValue);
        if (healthValue == 0)
        {
            audioSourceLow.Stop(); 
            audioSourceMedium.Stop();
            SceneManager.LoadScene(2);
        }
    }

    void UpdateFillColor(float value)
    {
        if (fillImage != null)
        {
            float percentage = value / Slider1.maxValue;

            if (percentage > 0.65f)
            {
                fillImage.color = safe;
            }
            else if (percentage > 0.2f)
            {
                fillImage.color = meh;
            }
            else
            {
                fillImage.color = danger;
            }
        }
    }

    void UpdateAudio(float percentage)
    {
        if (audioSourceLow != null && audioSourceMedium != null)
        {
            if (percentage > 0.2f && percentage <= 0.65f)
            {
                float adjustedPercentage = (percentage - 0.2f) / 0.45f; 
                audioSourceMedium.volume = Mathf.Lerp(0.5f, 0.1f, adjustedPercentage); 
                audioSourceMedium.pitch = Mathf.Lerp(1.5f, 1f, adjustedPercentage); 

                if (!audioSourceMedium.isPlaying)
                {
                    audioSourceMedium.Play();
                }
            }
            else
            {
                audioSourceMedium.volume = 0f;
                audioSourceMedium.Stop();
            }

            if (percentage > 0f && percentage <= 0.2f)
            {
                float adjustedPercentage = percentage / 0.2f; 
                audioSourceLow.volume = Mathf.Lerp(0.1f, 0.5f, 1 - adjustedPercentage); 
                if (!audioSourceLow.isPlaying)
                {
                    audioSourceLow.Play();
                }
            }
            else
            {
                audioSourceLow.volume = 0f;
                audioSourceLow.Stop();
            }
        }
    }
}