///code generated by chatgpt, the prompt is "generate a code for the smooth color gradient process in the slider component with max and min value and decrease by time, with color-change thresholds of 65% and 20%."
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class BarGradient : MonoBehaviour
{
    public Slider Slider1;
    public Image fillImage;
    public Color safe = Color.green;  
    public Color meh = Color.yellow;   
    public Color danger = Color.gray;  
    public static float healthValue;  

    void Start()
    {
        healthValue = Slider1.maxValue; 
        Slider1.value = healthValue;    
        UpdateFillColor(Slider1.value); 
    }

    void Update()
    {
        Slider1.value -= Time.deltaTime;
        if (Slider1.value < 0)
        {
            Slider1.value = 0;
        }
        healthValue = Slider1.value;
        UpdateFillColor(Slider1.value);
        if (healthValue == 0)
        {
            SceneManager.LoadScene(2); 
        }
    }

    void UpdateFillColor(float value)
    {
        if (fillImage != null)
        {
            float percentage = value / Slider1.maxValue; 

            if (percentage > 0.65f)
            {
                fillImage.color = safe; 
            }
            else if (percentage > 0.2f)
            {
                fillImage.color = meh; 
            }
            else
            {
                fillImage.color = danger; 
            }
        }
    }
}


